"""
Paper model representing uploaded research documents.

This is the core entity in the RAG system - each paper is chunked,
embedded, and stored in the vector database for semantic search.
"""

from sqlalchemy import Column, String, Integer, JSON, Boolean, Float, Index
from sqlalchemy.orm import relationship

from src.database.models.base import BaseModel
from src.database.models import TimestampMixin


class Paper(BaseModel, TimestampMixin):
    __tablename__ = "papers" 
    """
    Represents a research paper uploaded to the system.
    
    Why this model exists:
    - Central entity for RAG system (papers are what users query)
    - Stores metadata for filtering and display
    - Tracks processing pipeline status
    - Links to chunks for retrieval
    
    Workflow:
    1. User uploads PDF → Paper record created (processed=False)
    2. PDF extracted → Metadata populated (title, authors, etc.)
    3. Chunks created → chunk_count updated
    4. Embeddings generated → processed=True
    
    Relationships:
        - One paper → Many chunks (1:N)
        - One paper → Many citations (1:N, through queries)
    """
        
    # ========================================================================
    # IDENTIFICATION FIELDS
    # ========================================================================
    
    paper_name = Column(
        String(500),
        unique=True,  # Why unique: Prevent duplicate uploads
        index=True,   # Why indexed: Fast duplicate checking
        nullable=False,
        # Why this field:
        # - Extracted from filename (e.g., "attention_is_all_you_need")
        # - Human-readable identifier
        # - Used in API responses and citations
        # Example: "transformer_paper.pdf" → paper_name="transformer_paper"
    )
    
    title = Column(
        String(1000),  # Length 1000: Academic titles can be very long
        nullable=False,
        # Why this field:
        # - Extracted from PDF metadata or first page
        # - Displayed in search results
        # - Used in citations: "Found in: Attention Is All You Need"
        # - Improves user experience over filename
    )
    
    # ========================================================================
    # METADATA FIELDS (Extracted from PDF)
    # ========================================================================
    
    authors = Column(
        JSON,  # Array of strings: ["Vaswani, A.", "Shazeer, N.", ...]
        default=list,
        nullable=True,
        # Why JSON:
        # - Variable number of authors (1-20+)
        # - Preserves order
        # - Easily serializable for API responses
        # Use cases:
        # - Display: "By Vaswani et al."
        # - Search: "Papers by author X"
        # - Analytics: "Most cited author"
    )
    
    year = Column(
        Integer,
        index=True,  # Why indexed: Enables year-based filtering
        nullable=True,
        # Why this field:
        # - Extracted from PDF metadata or parsed from text
        # - Filters: "Show papers from 2020-2023"
        # - Sorting: "Newest first"
        # - Relevance: Prefer recent papers in some contexts
    )
    
    keywords = Column(
        JSON,  # Array of strings: ["NLP", "transformers", "attention"]
        default=list,
        nullable=True,
        # Why this field:
        # - Extracted from PDF or generated by NLP
        # - Improves search: User searches "attention" → matches this paper
        # - Topic clustering: Group papers by keyword
        # - Recommendation: "Related papers on 'transformers'"
    )
    
    abstract = Column(
        String(5000),  # Max 5000 chars (most abstracts are 200-500)
        nullable=True,
        # Why this field:
        # - High-level summary of paper
        # - Quick preview in search results
        # - Used in RAG context if available
        # - Helps users decide if paper is relevant
    )
    
    # ========================================================================
    # FILE MANAGEMENT FIELDS
    # ========================================================================
    
    filename = Column(
        String(500),
        nullable=False,
        # Why this field:
        # - Original upload filename (e.g., "paper.pdf")
        # - Duplicate detection
        # - Debugging: "Which file did user upload?"
    )
    
    file_path = Column(
        String(1000),
        unique=True,  # Why unique: One file per path
        nullable=False,
        # Why this field:
        # - Path on disk: "/uploads/abc-123-def.pdf"
        # - Enables reprocessing: Read original PDF again
        # - Required for file deletion
        # - Audit trail: Verify file still exists
    )
    
    # ========================================================================
    # PROCESSING METADATA
    # ========================================================================
    
    total_pages = Column(
        Integer,
        default=0,
        nullable=False,
        # Why this field:
        # - Indicates document size
        # - Quality check: 0 pages = extraction failed
        # - Analytics: "Average pages per paper"
        # - User info: "42-page document"
    )
    
    chunk_count = Column(
        Integer,
        default=0,
        nullable=False,
        # Why this field:
        # - Tracks chunking completion
        # - Quality metric: Low count may indicate poor extraction
        # - Performance: More chunks = more vectors to search
        # - Debugging: Verify chunking worked
    )
    
    quality_score = Column(
        Float,  # Range: 0.0 to 1.0
        default=0.0,
        nullable=False,
        # Why this field:
        # - Measures PDF extraction quality
        # - Calculated from: text density, section detection, etc.
        # - Filters: "Only show high-quality papers (>0.8)"
        # - Alerts: Warn user if quality < 0.5
        # Example: Scanned PDFs may have low quality scores
    )
    
    format_type = Column(
        String(50),  # Values: "standard", "report", "commentary", "preprint"
        default="standard",
        nullable=False,
        # Why this field:
        # - Different formats need different chunking strategies
        # - "report" may have executive summary
        # - "commentary" may lack traditional sections
        # - Helps customize processing pipeline
    )
    
    sections = Column(
        JSON,  # Array of objects: [{"name": "Intro", "page_start": 1, ...}, ...]
        default=list,
        nullable=True,
        # Why JSON:
        # - Preserves document structure
        # - Variable number of sections
        # - Used to populate chunks' section metadata
        # Example:
        # [
        #   {"name": "Abstract", "page_start": 1, "page_end": 1},
        #   {"name": "Introduction", "page_start": 2, "page_end": 4}
        # ]
    )
    
    processed = Column(
        Boolean,
        default=False,
        index=True,  # Why indexed: Frequent filtering by processing status
        nullable=False,
        # Why this field:
        # - Pipeline status tracking
        # - False: Upload complete, processing pending
        # - True: Chunks created, embeddings generated
        # Queries:
        # - "Show unprocessed papers" → processed=False
        # - "Only searchable papers" → processed=True
    )
    
    # ========================================================================
    # RELATIONSHIPS
    # ========================================================================
    
    chunks = relationship(
        "Chunk",
        back_populates="paper",
        cascade="all, delete-orphan",
        # Why cascade="all, delete-orphan":
        # - When paper is deleted, auto-delete all its chunks
        # - Prevents orphaned chunks in database
        # - Maintains referential integrity
        # Example: DELETE paper with id=5 → also deletes chunks with paper_id=5
    )
    
    # ========================================================================
    # CUSTOM INDEXES
    # ========================================================================
    
    __table_args__ = (
        # Composite index for common query: unprocessed papers by date
        Index('idx_papers_processed_created', 'processed', 'created_at'),
        # Use case: "Show oldest unprocessed papers first"
    )
    
    def __repr__(self):
        """String representation for debugging and logging"""
        return (
            f"<Paper(id={self.id}, name='{self.paper_name}', "
            f"processed={self.processed}, chunks={self.chunk_count})>"
        )
